name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_REDIS_ADDR: localhost:6379
      TEST_MYSQL_DSN: dev:dev@tcp(127.0.0.1:3306)/layerhub?parseTime=true
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install migrate
        run: go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run dependencies
        run: docker compose up -d

      - name: Test
        run: go test -v ./...
